### Registro de un usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Tu nombre",
  "email": "test@test.com",
  "password": "123456"
}

### Inicio de sesión de un usuario
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

### Obtener todos los hábitos (SUSTITUIR <token> por el que nos devuelva el login)
GET http://localhost:3000/habits
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE

### Crear un hábito
POST http://localhost:3000/habits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE

{
  "name": "TEST WEEKLY",
  "category": "streak",
  "color": "#ff00c8",
  "targetFrequency": "weekly",
  "timesPerPeriod": 3
}

### Editar un hábito
PUT http://localhost:3000/habits/<id>
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE

{
  "name": "Ejercicio actualizado",
  "category": "Salud",
  "color": "#6366f1",
  "targetFrequency": "weekly",
  "timesPerPeriod": 3
}

### Eliminar un hábito
DELETE http://localhost:3000/habits/<id>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE

### Obtener todos los logs
GET http://localhost:3000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE

### Obtener logs filtrados por hábito
GET http://localhost:3000/logs?habitId=6a4777ff38a3353df27e0241
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE

### Obtener logs filtrados por mes
GET http://localhost:3000/logs?month=2026-06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE

### Obtener logs filtrados por hábito y mes
GET http://localhost:3000/logs?habitId=6a4cc77e1efb73142638840b&month=2026-06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE

### Crear o actualizar un log
POST http://localhost:3000/logs/6a575e8264ec69e1734b1eb1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE

{
  "date": "2026-07-12T23:30:00",
  "note": "completado"
}

### Racha
GET http://localhost:3000/stats/6a575e8264ec69e1734b1eb1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDYxNzg2ZjBkZGQwYmJhOTExNzlhOCIsImlhdCI6MTc4NDEwODczNSwiZXhwIjoxNzg0MTk1MTM1fQ.Nx95XJQU9BUUKGdANnzfX3rjp5nutfDHj-y77bJ4oOE